resources:
  - name: source-code-from-github
    type: git
    source:
      uri: https://github.com/santiagovm/poc-service-virtualization
      branch: spike-ci

jobs:
  - name: build-and-test
    public: true
    plan:
      - get: source-code-from-github
        trigger: true
      - task: run-build-and-test
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: {repository: golang}
          inputs:
            - name: source-code-from-github
          caches:
            - path: source-code-from-github/.gradle
          run:
            path: ./source-code-from-github/ci/build-and-test.sh
